/* eslint-disable */
/* @ts-nocheck */
/* prettier-ignore */
/* This file is automatically generated. Please do not modify it manually. */
import type { GraphQLClient } from 'graphql-request';
import type { GraphQLClientRequestHeaders } from 'graphql-request/build/cjs/types';
import * as Operations from './graphql';



export type SdkFunctionWrapper = <T>(action: (requestHeaders?:Record<string, string>) => Promise<T>, operationName: string, operationType?: string) => Promise<T>;


const defaultWrapper: SdkFunctionWrapper = (action, _operationName, _operationType) => action();

export function getSdk(client: GraphQLClient, withWrapper: SdkFunctionWrapper = defaultWrapper) {
  return {
    allEvents(variables?: Operations.AllEventsQueryVariables, requestHeaders?: GraphQLClientRequestHeaders): Promise<Operations.AllEventsQuery> {
      return withWrapper((wrappedRequestHeaders) => client.request<Operations.AllEventsQuery>(Operations.AllEventsDocument, variables, {...requestHeaders, ...wrappedRequestHeaders}), 'allEvents', 'query');
    }
  };
}
export type Sdk = ReturnType<typeof getSdk>;