query singleEventImage($photoId: ID!) {
  EventImage(id: $photoId) {
    _id
    title
    url
    image {
      asset {
        _id
        metadata {
          lqip
          blurHash
        }
        assetId
      }
    }
  }
}
